### PR TITLE
Ensure that Istio application endpoint is reachable from Meshery

### LINKED ISSUE #27: The application deployed is not reachable to Meshery
#### Description

The application deployed by SMP github action is not reachable to Meshery.

#### Expected Behavior

Root cause:
1. The default endpoint_url is Istio ingress url + ingress port, which returns 404 status code to Meshery. 
2. `minikube tunnel` is easy to be killed.

#### Screenshots/Logs

image

#### Environment:
- Meshery Version: 
- Kubernetes Version: 
- Host OS:
- Browser:

### PR DESCRIPTION
**Pull request by gyohuangxin**
Signed-off-by: Xin Huang <xin1.huang@intel.com>

**Description**

This PR fixes #27 

1. Replace `minikube tunnel` command with `minikube tunnel &> /dev/null &` to avoid the tunnel getting killed.
2. Change the default endpoint_url to make sure it's reachable from Meshery.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by gyohuangxin** [comment]
@navendu-pottekkat I've tested it and it works, can you review this? Thanks.
image

**Comment by leecalcote** [comment]
@SunkuRanganath fyi

**Review by navendu-pottekkat — APPROVED** [review]
Thank you for the fix @gyohuangxin 🚀 

Looks good to me. I missed the `/productpage` path as well!

**Comment by s1ntaxe770r** [comment]
Thank you @gyohuangxin !

**Pull request merged**
