### PR TITLE
chore: added links to ISSUE_TEMPLATE

### LINKED ISSUE #80: Issue Template Updates for Figma link
### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

### Desired Situation
Each template that has a reference to Figma in its resources section should an invite link added.

### Implementation 
```
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```

**Acceptance Tests**
All references to Figma include the "open invite" link.

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### PR DESCRIPTION
**Pull request by Yana-Gupta**
**Description**

This PR fixes #80 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Yana-Gupta** [comment]
@thisiskaransgit Can you review the pr.

**Review by thisiskaransgit — COMMENTED** [review]
@Yana-Gupta, kindly update the remaining issue templates too.

**Comment by Yana-Gupta** [comment]
Hey, @thisiskaransgit I have added updated the ISSUES_TEMPLATE.

**Review by leecalcote — APPROVED** [review]
Good eye, @thisiskaransgit! 

Thank you, @Yana-Gupta 👏

**Pull request merged**
