### PR TITLE
Add Meshes: Kuma, App Mesh, Consul, Cilium

### LINKED ISSUE #51: Enable other service meshes performance tests
#### Current Behavior

We have included Istio, Linkerd, OSM performance tests.

#### Desired Behavior

We should enable other service meshes performance tests listed on https://smp-spec.io/dashboard.

- [ ] Consul
- [ ] App Mesh
- [ ] Kuma
- [ ] Cilium

#### Implementation

Writing bash scripts for each mesh is time consuming, so we should use `mesheryctl` to deploy them.
And we should use `mesheryctl app onboard` to deploy sample apps if https://github.com/layer5io/meshery-smp-action/pull/48 is readay.

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### PR DESCRIPTION
**Pull request by gyohuangxin**
Signed-off-by: Huang Xin <xin1.huang@intel.com>

**Description**

This PR fixes #51 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Ready to try this out?

**Comment by gyohuangxin** [comment]
@leecalcote Yes, I'm working on it. One question is that no every service mesh has its own demo apps, I found Kuma has one but app mesh, consul and cilium may not. Can we use Istio's bookinfo app as a alternative?

**Comment by hershd23** [comment]
Found this for consul :- https://github.com/hashicorp/learn-consul-k8s-hashicups/tree/main/hashicups

I guess this might work

**Comment by Zanda256** [comment]
This will be a lot of heavy lifting. Maybe for cilium, since it's a new project and the makers haven't released a sample app yet.

**Comment by gyohuangxin** [comment]
> Another thought, is it worth making one common pattern, say bookinfo for all service mesh adapters. This gives us a common pattern to test for SMP.... if that's something we want

@hershd23 Yes, I think we should. I will try `mesheryctl pattern apply` instead of `mesheryctl app aboard`. In the future, we should make it configurable.

**Comment by gyohuangxin** [comment]
I failed to deploy app-mesh and cilium adapters, 
- For app-mesh adapter, I use command `mesheryctl mesh deploy adapter meshery-app-mesh:10000 --token "./.github/workflows/auth.json"`, but it will never choose to deploy app-mesh in console: 
```
Failed to open Meshery in browser, please point your browser to http://192.168.49.2:31552/ to access Meshery.
Verifying prerequisites...
25l
Use the arrow keys to navigate:↓↑→←
? Select a Service Mesh from the list: 
▸LINKERD
    CONSUL
    KUMA
    OPEN_SERVICE_MESH
↓   NGINX_SERVICE_MESH
Use the arrow keys to navigate:↓↑→←
? Select a Service Mesh from the list: 
▸LINKERD
    CONSUL
    KUMA
    OPEN_SERVICE_MESH
↓   NGINX_SERVICE_MESH
Use the arrow keys to navigate:↓↑→←
? Select a Service Mesh from the list: 
▸LINKERD
    CONSUL
    KUMA
    OPEN_SERVICE_MESH
↓   NGINX_SERVICE_MESH
✔LINKERD
```
https://github.com/gyohuangxin/meshery-smp-action/runs/7183605286?check_suite_focus=true#step:4:88
- For cilium adapter, I use command `mesheryctl mesh deploy adapter meshery-cilium:10000 --token "./.github/workflows/auth.json"`, but it says `Adapter for required mesh not found`: https://github.com/gyohuangxin/meshery-smp-action/runs/7183605817?check_suite_focus=true#step:4:52`

@leecalcote Do you have any ideas, is my command wrong?

**Comment by leecalcote** [comment]
Still in draft?

**Pull request closed without merging**
