### PR TITLE
Rename pattern to design cmd in scripts

### PR DESCRIPTION
**Pull request by alphaX86**
**Description**

This PR fixes https://github.com/meshery/meshery/issues/10592

**Notes for Reviewers**
~DON'T MERGE UNLESS https://github.com/meshery/meshery/pull/11051 is merged!~
Update: PR is merged. Good to go

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by gyohuangxin** [comment]
Is it ready for review?

**Comment by alphaX86** [comment]
Ready. But requires that PR 10592 in Meshery to be reviewed and merged. Only then I'll make this PR as active

**Comment by gyohuangxin** [comment]
@alphaX86 Understand. Thank you for your explanation.

**Review by lekaf974 — APPROVED** [review]
LGTM

**Review by gyohuangxin — APPROVED** [review]
LGTM

**Comment by alphaX86** [comment]
Thanks @gyohuangxin @lekaf974

**Pull request merged**
