### PR TITLE
Add more logs during the meshery installation.

### PR DESCRIPTION
**Pull request by gyohuangxin**
Signed-off-by: Huang Xin <xin1.huang@intel.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by gyohuangxin** [comment]
I added more logs during meshery installation, so that we can check the meshery status and debug more easily.
@leecalcote @hershd23 @alphaX86

**Comment by hershd23** [comment]
Great @gyohuangxin

**Comment by leecalcote** [comment]
@Revolyssup @AugustasV fyi

**Comment by AugustasV** [comment]
@leecalcote in my opinion there was no need to merge such changes into master.
It was enough just to change how pipeline is triggered inside fork and add those lines for testing there

**Pull request merged**
