### PR TITLE
Fix scheduled builds

### LINKED ISSUE #29: Define benchmark test configurations
#### Current Behavior

The [Scheduled Benchmark Tests](https://github.com/layer5io/meshery-smp-action/blob/master/.github/workflows/scheduled-benchmarks.yml) workflow runs performance benchmark tests at regular intervals and captures the test results.

It runs the tests defined in these two test configuration files.

* [soak-test.yaml
](https://github.com/layer5io/meshery-smp-action/blob/master/.github/soak-test.yaml)
* [load-test.yaml](https://github.com/layer5io/meshery-smp-action/blob/master/.github/load-test.yaml)

These test configurations are not yet defined properly.

#### Desired Behavior

Define proper test configurations to run benchmark tests.

#### Implementation

Update the test configuration files linked above.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### PR DESCRIPTION
**Pull request by AugustasV**
**Description**

**Notes for Reviewers**
Was looking into this issue why builds been failing, find out that Open Service Mesh (OSM) CLI version was changed, also tried to simplify code to see what can I do to make it work.

Unsuccessful run on master here :- https://github.com/layer5io/meshery-smp-action/runs/5204098138?check_suite_focus=true
Successful run on your local fork :- https://github.com/AugustasV/meshery-smp-action/runs/5204058656?check_suite_focus=true

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
// @hershd23

**Comment by leecalcote** [comment]
Thank you, @AugustasV! 👍

**Comment by gyohuangxin** [comment]
@AugustasV Thank you, and this code looks good to me. But a little suggestion, could you rebase your 5 commits to one commit,  because they are doing the same thing, which will help keep commit log clean.

**Review by navendu-pottekkat — APPROVED** [review]

**Comment by hershd23** [comment]
Hi @AugustasV great work and thank you for taking up this problem.

Just a couple of suggestions :- 
1. As @gyohuangxin has said if you could squash these 5 commits into one, that would really help up keeping the log clean. You can follow the instructions given here. https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git Both the highest voted and the accepted answer should work
2. Do link the successful workflow run post the change you have made.

I believe after this your changes would be ready to merge

**Comment by AugustasV** [comment]
Thank you for suggestions and tips, squashed.

**Review by hershd23 — APPROVED** [review]
Approved

**Review by gyohuangxin — APPROVED** [review]
Thanks.

**Review by navendu-pottekkat — APPROVED** [review]
The PR was linked to the wrong issue. Removed that from the PR description.

LGTM.

**Pull request merged**
