### PR TITLE
Cherry-pick self hosted to master

### LINKED ISSUE #44: Cherry-pick self-hosted commit to master branch
Regarding https://github.com/layer5io/meshery-smp-action/issues/38, we have implement running SMP on self-hosted CNCF cluster, and codes have been merged into self-hosted branch. We should cherry-pick it to master branch. 

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### PR DESCRIPTION
**Pull request by gyohuangxin**
**Description**

This PR fixes #44 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by gyohuangxin** [comment]
@leecalcote Can you merge this? And then two github secrets should be added to let it work.

image


1. CNCF CIL Token
We use CNCF projects api key to use CNCF CIL's apis in our jobs, so we should add a secret named "CNCF_CIL_TOKEN" contains  the api key, copy from equinix console page:
image



 2. Personal access token
 We use a github personal access token [here](https://github.com/gyohuangxin/meshery-smp-action/blob/724977d6d7be0574adbbb9bcf8c4df4e9b0b4df9/.github/workflows/configurable-benchmark-test-self-hosted.yaml#L129) to give jobs the access to delete github runners. So we should add a secret named "PAT" contains a personal access token which have the access to this repo. If we don't have a personal access token, we can create one: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
 
 
I haven't the permission to add above two secrets in this repo, so can you add them or give me a accessible role?

**Comment by gyohuangxin** [comment]
@leecalcote Can you merge this? And then two github secrets should be added to let it work.

image


1. CNCF CIL Token
We use CNCF projects api key to use CNCF CIL's apis in our jobs, so we should add a secret named "CNCF_CIL_TOKEN" contains  the api key, copy from equinix console page:
image



 2. Personal access token
 We use a github personal access token [here](https://github.com/gyohuangxin/meshery-smp-action/blob/724977d6d7be0574adbbb9bcf8c4df4e9b0b4df9/.github/workflows/configurable-benchmark-test-self-hosted.yaml#L129) to give jobs the access to delete github runners. So we should add a secret named "PAT" contains a personal access token which have the access to this repo. If we don't have a personal access token, we can create one: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
 
 
I haven't the permission to add above two secrets in this repo, so can you add them or give me a accessible role?

**Comment by gyohuangxin** [comment]
@leecalcote  @hershd23  Can you review this and give some advice about above permission issue? Thanks.

**Comment by leecalcote** [comment]
This folder in the community drive has a GitHub Process doc, which will be helpful reference and to which the new CIF token can be noted - https://drive.google.com/drive/folders/1O7TPo1FYkEYcUhQPx6hAzxPho7pWgtIp

**Comment by gyohuangxin** [comment]
@leecalcote Thanks for giving me the privileges and I can add "CNCF_CIL_TOKEN" in this repo. I raised a PR #46  to change PAT name used in scripts to "GH_ACCESS_TOKEN", can you merge it too?

**Comment by leecalcote** [comment]
Awesome. You bet.

**Pull request merged**
