### PR TITLE
Edit bash scripts for `linkerd` and `osm`

### PR DESCRIPTION
**Pull request by alphaX86**
Signed-off-by: Aadhitya A <aadhitya864@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**
Tests are being run. So, PR is WIP

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by alphaX86** [comment]
Ok seems I found a tiny bug in the install script... maybe fixing that should resolve the trick
https://github.com/meshery/meshery.io/blob/58e355bea9e558f91bc152af4cc8c3eff8a35e06/install#L237

**Comment by gyohuangxin** [comment]
@alphaX86 Thanks for updating this.

**Review by gyohuangxin — APPROVED** [review]
LGTM

**Comment by gyohuangxin** [comment]
@alphaX86 There is still 500 error when deploying app on OSM: https://github.com/layer5io/meshery-smp-action/runs/8124771122?check_suite_focus=true#step:5:44

**Comment by alphaX86** [comment]
@gyohuangxin I wonder if its the issue on OSM mesh adapter, could you confirm if its working fine on linkerd side?

**Comment by gyohuangxin** [comment]
@alphaX86 It seems working fines on linkerd side https://github.com/layer5io/meshery-smp-action/runs/8127842569?check_suite_focus=true#step:5:55

**Comment by alphaX86** [comment]
Gotcha... So the issue is on `osm` adapter. I'll fix this in a new PR 👍

**Comment by gyohuangxin** [comment]
@alphaX86 Thanks!

**Pull request merged**
